joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

wheelchair_controller:
  #Publish to TF directly or not
  enable_odom_tf: false
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'wheelchair_base_link_left_wheel_joint'
  right_wheel : 'wheelchair_base_link_right_wheel_joint'
  publish_rate: 100.0               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.60
  wheel_radius : 0.17

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: base_footprint #default: base_link

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.8  # m/s
      min_velocity           : -0.8 # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.0  # m/s^2
      min_acceleration       : -1.0 # m/s^2
      has_jerk_limits        : true
      max_jerk               : 5.5  # m/s^3 #this oscillates when stopping
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 0.25  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1.0  # rad/s^2
      has_jerk_limits        : true
      max_jerk               : 5.5  # rad/s^3 #this oscillates when stopping - higher the better