joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

wheelchair_controller:
  #Publish to TF directly or not
  enable_odom_tf: false
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'wheelchair_base_link_left_wheel_joint'
  right_wheel : 'wheelchair_base_link_right_wheel_joint'
  publish_rate: 100.0               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.60
  wheel_radius : 0.17

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: base_footprint #default: base_link

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.3  # m/s  #here's the forward speed
      min_velocity           : -0.3 # m/s  #here's the back speed
      has_acceleration_limits: true
      max_acceleration       : 0.5  # m/s^2 #rate of acceleration
      min_acceleration       : -0.4 # m/s^2
      has_jerk_limits        : true
      max_jerk               : 3.0  # m/s^3 #margin of error bounce
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 0.5  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.3  # rad/s^2
      has_jerk_limits        : true
      max_jerk               : 1.5  # rad/s^3

#Publish to TF directly or not
enable_odom_tf: false

#Name of frame to publish odometry in
#odom_frame_id: odom
publish_tf: false
# Publish the velocity command to be executed. 
# It is to monitor the effect of limiters on the controller input.
publish_cmd: true
